=== JSillero/LenguajeDeMarcas/ejercicios/tema7/xsd/ej6_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="personas">
        <xs:complexType>
            <xs:all>
                <xs:element name="persona"
                            minOccurs="0"
                            maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="datos">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos" type="xs:string"/>
                                        <xs:element name="dni" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comentario" type="xs:string"/>
                            <xs:element name="forma-de-pago" type="xs:string">
                                <xs:complexType>
                                
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:all>
                        <xs:attribute name="fech-nac" type="xs:date"/>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JSillero/LenguajeDeMarcas/ejercicios/tema7/xsd/ej6_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ej6_2.xsd">
    <persona fech-nac="1996-12-18">
        <datos >
            <nombre>Nombre</nombre>
            <apellidos>Aleppido</apellidos>
            <dni>DNI</dni>
        </datos>
        <comentario> CAASFASEAFEA</comentario>
        <forma-de-pago numero="111111111">Tarjeta</forma-de-pago>
    </persona>
    <persona fech-nac="1996-12-18">
        <datos>
            <nombre>Nombre</nombre>
            <apellidos>Aleppido</apellidos>
            <dni>DNI</dni>
        </datos>
        <comentario> CAASFASEAFEA</comentario>
        <forma-de-pago numero="111111111">Transferencia</forma-de-pago>
    </persona>


</personas>
